'use strict';

const COMPOSER_MAX_VISIBLE_LINES = 5;
const COMPOSER_LINE_HEIGHT = 20;
const COMPOSER_VERTICAL_PADDING = 16;
const COMPOSER_MAX_HEIGHT =
  COMPOSER_LINE_HEIGHT * COMPOSER_MAX_VISIBLE_LINES + COMPOSER_VERTICAL_PADDING;

module.exports = {
  COMPOSER_MAX_VISIBLE_LINES,
  COMPOSER_LINE_HEIGHT,
  COMPOSER_VERTICAL_PADDING,
  COMPOSER_MAX_HEIGHT,
};
